// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID        int64     `json:"id"`
	ImageUrl  string    `json:"image_url"`
	Name      string    `json:"name"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}
